edupulse/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static
from dashboard.views import DashboardView

from . import views
from .views import  ManageAttendanceView,SaveWeeklyReportsView, DashboardTestView,StudentAttendanceReport

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('upload_file/',include('uploadFile.urls')), #namespace is the same name mentioned in urls.py file app_name 
    # path('',views.DashboardView.as_view(), name='dashboard2'),
    path('',DashboardView.as_view(), name='dashboard'),
    
    path('test/',DashboardTestView.as_view(), name='dashboard-testing'),
  
    path('manage-attendance/', ManageAttendanceView.as_view(),name='manage-attendance'),
    path('save-weekly-reports/', SaveWeeklyReportsView.as_view(), name='save_weekly_reports'),
    path('student-attendance-report/', StudentAttendanceReport.as_view(), name='student_attendance_report'),
    path('wc_current_programs/',include('program.urls')),
    path('attendance/',include('attendance.urls')),
    path('user/',include('customUser.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path("dashboard/", include("dashboard.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

report/urls.py
from django.urls import path,include
from .views import AttendanceListView,AttendanceCreateView, mark_attendance, WeeklyReportView,edit_weekly_report,edit_attendance

from uploadFile.views import Attendance_Upload_View,Canvas_weekly_report_upload_view

urlpatterns = [
    
    path('take-attendance/<uuid:pk>/', AttendanceCreateView.as_view(),name='take_attendance'),
    path('<uuid:pk>/', AttendanceListView.as_view(),name='attendance_list'),
    path('edit/<uuid:pk>/<str:attendance_date>', edit_attendance,name='edit-attendance'),
    path('upload-attendance/<uuid:pk>', Attendance_Upload_View,name='upload_attendance'),
    path('create-attendance/<uuid:pk>/', mark_attendance,name='create-attendance'),
    path('weekly-report/<uuid:pk>/', WeeklyReportView.as_view(),name='weekly_report_list'),
    # path('manage-attendance', ManageAttendance.as_view(),name='manage-attendance'),
    path('weekly-report/<uuid:pk>/upload-canvas-report/<int:week_number>/', Canvas_weekly_report_upload_view,name='upload_canvas_report'),
    
    path('weekly-report/<uuid:pk>/edit/<int:week_number>', edit_weekly_report,name='edit_weekly_report'),
    
]

report/models.py
from django.db import models
from base.models import BaseModel
from customUser.models import Student  # Import the Student model
from program.models import ProgramOffering, CourseOffering
from django.utils import timezone
from django.db import models
from datetime import date
from django.db.models import Count, F



from utils.function.BaseValues_List import ATTENDANCE_CHOICE, ENGAGEMENT_CHOICE, ACTION_CHOICE, FOLLOW_UP_CHOICE, PERFORMANCE_CHOICE, ASSESSMENT_CHOICE


    
    
class Attendance(BaseModel):
    
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True, blank=True,related_name='attendances')
    
    # program offering will not connect with attendance
    program_offering = models.ForeignKey(ProgramOffering, on_delete=models.CASCADE, null=True, blank=True,related_name='attendances')
    
    course_offering = models.ForeignKey(CourseOffering, on_delete=models.CASCADE, null=True, blank=True ,related_name="attendances")  
    is_present = models.CharField(max_length=255,choices=ATTENDANCE_CHOICE,default="present", null=True, blank=True)  
    attendance_date = models.DateField(default=timezone.now, null=True, blank=True)
    remark=models.TextField(null=True,blank=True,max_length=255)
    weekly_reports = models.ManyToManyField('WeeklyReport', related_name='attendances')
    
    # new attributes 
    week_no=models.PositiveIntegerField()
    session_no=models.PositiveIntegerField()

   
    
    class Meta:
        unique_together = ('student', 'course_offering','attendance_date','week_no','session_no')

    def __srt__(self):
        return f"{self.student} - {self.course_offering} - {self.attendance_date}-{self.is_present}"

class WeeklyReport(BaseModel):
    # ENGAGEMENT_CHOICE=[
    #     ('na','N/A'),
    #     ('on track canvas','On Track - CANVAS'),
    #     ('on track assessment','On Track - Assessment'),
    #     ('on track learning activity','On Track - Learning Activity'),
    #     ('on track blended','On Track - Blended'),
    #     ('not engaged','Not Engaged'),
    # ]
    # ACTION_CHOICE=[
    #     ('na','N/A'),
    #     ('follow up email and call','Follow Up Email and Call'),
    #     ('pastoral care','Pastoral Care'),
    #     ('personalized study plan/Extra session','Personalized Study Plan /Extra Session'),
    #     ('emergency contact','Emergency Contact'),
    #     ('other','Other'),
    # ]
    # FOLLOW_UP_CHOICE=[
    #     ('na','N/A'),
    #     ('warning letter 1','Warning Letter 1'),
    #     ('warning letter 2','Warning Letter 2'),
    # ]
    # PERFORMANCE_CHOICE=[
    #     ('na','N/A'),
    #     ('poor','POOR'),
    #     ('good','GOOD'),
    #     ('moderate','MODERATE'),
    # ]
    # ASSESSMENT_CHOICE=[
    #     ('na','N/A'),
    #     ('making progress','MAKING PROGRESS '),
    #     ('no progress','NO PROGRESS'),
    #     ('request extension','REQUEST EXTENSION'),
    #     ('submitted','SUBMITTED'),
    #     ('not submitted','NOT SUBMITTED'),
    #     ('failed','FAILED'),
    #     ('re-sit','RE-SIT'),
    # ]
    
    
    week_number=models.PositiveIntegerField(blank=True,null=True)
    # sessions will be list of all attendance in one week
    sessions=models.ManyToManyField(Attendance, verbose_name=("sessions"))
    engagement=models.CharField(choices=ENGAGEMENT_CHOICE,default="na",null=True,blank=True, max_length=255)
    action=models.CharField(choices=ACTION_CHOICE,null=True,blank=True, max_length=255,default='na')
    follow_up=models.CharField(choices=FOLLOW_UP_CHOICE,null=True,blank=True, max_length=255,default="na")
    course_offering=models.ForeignKey(CourseOffering, verbose_name=("Course Offering"), on_delete=models.CASCADE,null=True, blank=True ,related_name='weekly_reports')
    student=models.ForeignKey(Student, verbose_name=("Student"), on_delete=models.CASCADE,related_name='weekly_reports')
    no_of_pages_viewed_on_canvas=models.PositiveIntegerField(null=True,blank=True, default=0)
    login_in_on_canvas=models.BooleanField(default=False, blank=True,null=True)
    # at_risk Status
    assessment_status=models.CharField( choices=ASSESSMENT_CHOICE, max_length=255,null=True,blank=True,default="n/a")
    at_risk=models.BooleanField(default=False,null=True,blank=True)
    
    def get_week_number(self):
        start_date=self.course_offering.start_date
        end_date=self.course_offering.end_date
        
        attendance_dates = [session.attendance_date for session in self.sessions.all()]

        # Find the minimum attendance date
        min_attendance_date = min(attendance_dates) if attendance_dates else date.today()  # Use today's date if there are no attendance dates
        # Calculate the number of weeks between start_date and min_attendance_date
        num_weeks = (min_attendance_date - start_date).days // 7 + 1
        
        return num_weeks
        
        






class CourseResult(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True, blank=True)
    program_offering = models.ForeignKey(ProgramOffering, on_delete=models.CASCADE, null=True, blank=True)
    course_offering = models.ForeignKey(CourseOffering, on_delete=models.CASCADE)
    result_status_code=models.CharField(max_length=255,null=True,blank=True)
    result_status=models.CharField(max_length=255,null=True,blank=True)
    marks = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    result_status = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return f"{self.student} - {self.program_offering} - {self.course_offering}"

    class Meta:
        unique_together = ('student', 'program_offering', 'course_offering')


class StudentEnrollment(BaseModel):
    RESULT_CHOICE=[
        ('awaited','Awaited'),
        ('pass','Pass'),
        ('fail','Fail'),
        ('dropped','Dropped'),
    ]
    student=models.ForeignKey(Student, verbose_name='student', on_delete=models.CASCADE,related_name='student_enrollments')
    course_offering=models.ForeignKey(CourseOffering, verbose_name='course_offering', on_delete=models.CASCADE,related_name='student_enrollments')
    program_offering=models.ForeignKey(ProgramOffering, verbose_name='program_offering', on_delete=models.CASCADE,related_name='student_enrollments')
    status=models.BooleanField(default=True)
    result=models.CharField(choices=RESULT_CHOICE,null=True,blank=True, max_length=255,default='awaited')
    
    

templates/report/manage_attendance.html
{% extends "base.html" %}
{% block content %}
<section class="mt-10 mx-3 ">
    <h1  class='text-md text-black font-semibold mb-5'>Attendance Marking </h1>
    {% comment %} CO :{{course_offerings}} {% endcomment %}

    <form id="attendanceForm" method="POST" class="row g-3 flex j items-center text-center flex-row gap-4 w-full">
        {% csrf_token %}
        <!-- Add hidden fields to store filter values -->
        <input type="hidden" id="course_offering_filter" name="course_offering" value="">
        <input type="hidden" id="week_number_filter" name="week_number" value="">
        <input type="hidden" id="student_filter" name="student" value="">

        <div class="flex flex-row  justify-center items-center border-2 border-gray-200 bg-gray-100">
             <label for="id_course_offering" class='px-3 border-gray-400 text-sm bg-gray-100'>Course Offering</label>
            <select name="course_offering" id="id_course_offering" class="form-select border-gray-200 text-xs text-gray-500">
                <option value="" class=''>Select Course Offering</option>
                {% for offering in course_offerings %}
                    <option class='text-black ' value="{{ offering.temp_id }}">{{ offering.course.name }}</option>
                {% endfor %}
             
            </select>
        </div>
        
        <div class="flex flex-row  justify-center items-center border-2 border-gray-200 bg-gray-100">
            <label for="id_week_number" class='px-3 border-gray-400 text-sm bg-gray-100'>Week Number</label>
            <select id='id_week_number' name='week_number' class="form-select border-gray-200  text-xs text-gray-500">
                <option value="" class='text-xs'>Select Week Number</option>

            </select>
        </div>
        <div class="flex flex-row  justify-center items-center border-2 border-gray-200 bg-gray-100">
            <label for="id_student" class='px-3 border-gray-400 text-sm bg-gray-100'>Student Name</label>
            <select id="id_student" name="student" class="form-select border-gray-200  text-xs text-gray-500">
                <option value="">Select Student</option>
            </select>
        </div>
        <div class="bg-gray-100 text-gray-400 px-4 py-1 rounded-md text-md">
            <button type="button" id="resetBtn" class="btn btn-secondary">Clean</button>
        
        </div>
        <div class="bg-blue-400 text-white px-4 py-1 rounded-md text-md">
            
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </form>

    <div id="weeklyReportsContainer" class='mt-4 px-2 py-2 overflow-x-auto'>
        <!-- weekly reports  data will be displayed here -->
        Show weekly report 
        
        <!-- Weekly reports data will be displayed here -->
    </div>

</section>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
   

    $(document).ready(function () {
        // Function to update student dropdown based on selected course offering
        $('#id_course_offering').change(function () {
            var courseOfferingId = $(this).val();
            console.log("CO changed")
            $.ajax({
                url: '/manage-attendance/',
                type: 'GET',
                data: {
                    'course_offering_id': courseOfferingId,
                    
                },
                success: function (data) {
                     // Populate student
                    $('#id_student').empty();
                    $('#id_student').append($('<option>').text('Select Student').attr('value', ''));
                    $.each(data.students, function (index, student) {
                        $('#id_student').append($('<option>').text(student.first_name + ' ' + student.last_name).attr('value', student.id));
                    });
                    var studentFilter = localStorage.getItem('student_filter');
                    $('#id_student').val(studentFilter);

                    // Populate week numbers
                    $('#id_week_number').empty();
                    $('#id_week_number').append($('<option>').text('Select Week Number').attr('value', ''));
                    $.each(data.week_numbers, function (index, week) {
                        $('#id_week_number').append($('<option>').text("Week " + week).attr('value', week[0]));
                    });
                    var weekNumberFilter = localStorage.getItem('week_number_filter');
                    $('#id_week_number').val(weekNumberFilter);
                    
                    // Access weekly_reports from data
                   var weeklyReports = data.weekly_reports;
                   // Render weekly_reports in HTML
                   $('#weeklyReportsContainer').html(weeklyReports);

                   // Save selected values in local storage
                    localStorage.setItem('course_offering_filter', courseOfferingId);
                    localStorage.setItem('week_number_filter', $('#id_week_number').val());
                    localStorage.setItem('student_filter', $('#id_student').val());
                             

                }
            });
        });

         // Load values from local storage when the page is refreshed
        var courseOfferingFilter = localStorage.getItem('course_offering_filter');
        var weekNumberFilter = localStorage.getItem('week_number_filter');
        var studentFilter = localStorage.getItem('student_filter');

        $('#id_course_offering').val(courseOfferingFilter);
        
        $('#id_course_offering').val(courseOfferingFilter).trigger('change'); // Trigger change event
        
        
        

        // Function to submit form data and fetch attendance data
        $('#attendanceForm').submit(function (event) {
            event.preventDefault();
            $.ajax({
                url: '/manage-attendance/',
                type: 'POST',
                data: $(this).serialize(),
                success: function (data) {
                    $('#weeklyReportsContainer').html(data.html_content);
                    // Save selected values in local storage
                localStorage.setItem('course_offering_filter', $('#id_course_offering').val());
                localStorage.setItem('week_number_filter', $('#id_week_number').val());
                localStorage.setItem('student_filter', $('#id_student').val());

                }
            });
        });
       

        // Function to reset all dropdown values
        $('#resetBtn').click(function () {
            $('#id_course_offering').val('');
            $('#id_week_number').val('');
            $('#id_student').val('');

             // Clear weekly reports container
            $('#weeklyReportsContainer').html('');
            // Clear values from local storage
            localStorage.removeItem('course_offering_filter');
            localStorage.removeItem('week_number_filter');
            localStorage.removeItem('student_filter');
           
        });
    });
</script>

{% endblock %}

templates/report/student_attendance_report.html
{% extends "base.html" %}
{% load custom_tags %}
{% block content %}
    <section class='flex w-full flex-row gap-4'>
        
            <div class='flex w-1/3 flex-col gap-4'>
                {% for cat in main_filter_cat %}
                <button class='px-4 font-xs rounded-lg bg-gray-100'> {{cat|title}}</button>
                {% endfor %}
            </div>
            <div class='flex w-1/3 flex-col gap-4'>
                {% for cat in common_filter_cat_1 %}
                <button class='px-4 font-xs rounded-lg bg-gray-100'> {{cat|title}}</button>
                {% endfor %}
            </div>
            <div class='flex w-1/3 flex-col gap-4'>
                {% for cat in common_filter_cat_2 %}
                <button class='px-4 font-xs rounded-lg bg-gray-100'> {{cat|title}}</button>
                {% endfor %}
            </div>
        
   </section>
{% endblock content %}
    